// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEbZdtQCYBA8ElWw_HoRJYpoAYdECi7hQ',
    appId: '1:232493591448:web:ccc9e30d8098bb0a8b99ed',
    messagingSenderId: '232493591448',
    projectId: 'alhureyah-home-customer-serves',
    authDomain: 'alhureyah-home-customer-serves.firebaseapp.com',
    storageBucket: 'alhureyah-home-customer-serves.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-1O6nKEBG6HOQW3aeyYRKNChdwjZ-sB8',
    appId: '1:232493591448:android:72230e507b583a7d8b99ed',
    messagingSenderId: '232493591448',
    projectId: 'alhureyah-home-customer-serves',
    storageBucket: 'alhureyah-home-customer-serves.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKmRuN6AR_1go-RfmrgNGnvbnfP29bq2Q',
    appId: '1:232493591448:ios:822c0ee37d83642d8b99ed',
    messagingSenderId: '232493591448',
    projectId: 'alhureyah-home-customer-serves',
    storageBucket: 'alhureyah-home-customer-serves.appspot.com',
    iosClientId: '232493591448-dk74jn91hb5vdd5dnbhad29vnlfq7lib.apps.googleusercontent.com',
    iosBundleId: 'com.alhureyahhome.alhureyahCustomerService',
  );
}
